//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristRouteCatalog.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campsite
    {
        public Campsite()
        {
            this.Routes = new HashSet<Route>();
        }
    
        public int Id { get; set; }
        public int TypeId { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Route> Routes { get; set; }
    }
}
