//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristRouteCatalog.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteGeoPoint
    {
        public int Id { get; set; }
        public int RouteId { get; set; }
        public double Longitude { get; set; }
        public double Latitude { get; set; }
        public int OrderIndex { get; set; }
    
        public virtual Route Route { get; set; }
    }
}
