//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristRouteCatalog.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteDifficultyLevel
    {
        public RouteDifficultyLevel()
        {
            this.Routes = new HashSet<Route>();
        }
    
        public int Difficulty { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Route> Routes { get; set; }
    }
}
