//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristRouteCatalog.Core.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public Route()
        {
            this.RouteGeoPoints = new HashSet<RouteGeoPoint>();
            this.Campsites = new HashSet<Campsite>();
            this.WaterSources = new HashSet<WaterSource>();
            this.RouteImages = new HashSet<RouteImage>();
        }
    
        public int Id { get; set; }
        public int CreatorId { get; set; }
        public string Name { get; set; }
        public int DifficultyLevel { get; set; }
        public Nullable<long> Duration { get; set; }
        public string Description { get; set; }
        public string Seasons { get; set; }
        public string PublicTransport { get; set; }
    
        public virtual RouteDifficultyLevel RouteDifficultyLevel { get; set; }
        public virtual ICollection<RouteGeoPoint> RouteGeoPoints { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Campsite> Campsites { get; set; }
        public virtual ICollection<WaterSource> WaterSources { get; set; }
        public virtual ICollection<RouteImage> RouteImages { get; set; }
    }
}
