//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristRouteCatalog.Core.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TouristCatalogModelEntity : DbContext
    {
        public TouristCatalogModelEntity()
            : base("name=TouristCatalogModelEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Campsite> Campsites { get; set; }
        public DbSet<RouteDifficultyLevel> RouteDifficultyLevels { get; set; }
        public DbSet<RouteGeoPoint> RouteGeoPoints { get; set; }
        public DbSet<RouteImage> RouteImages { get; set; }
        public DbSet<Route> Routes { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<WaterSource> WaterSources { get; set; }
    }
}
