//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouristRouteCatalog.Core.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.EntityClient;
    using System.Data.Objects;

    public partial class TouristCatalogModelEntity : ObjectContext
    {
       #region Constructors
    
        /// <summary>
        /// Initializes a new ShopNBCEntities object using the connection string found in the 'ShopNBCEntities' section of the application configuration file.
        /// </summary>
        public TouristCatalogModelEntity()
            : base("name=TouristCatalogModelEntity", "TouristCatalogModelEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ShopNBCEntities object.
        /// </summary>
        public TouristCatalogModelEntity(string connectionString)
            : base(connectionString, "TouristCatalogModelEntity")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ShopNBCEntities object.
        /// </summary>
        public TouristCatalogModelEntity(EntityConnection connection)
            : base(connection, "ShopNBCEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion


        #region Partial Methods

        partial void OnContextCreated();

        #endregion
    
    }
}
